version: '3.8'

services:
  database:
    container_name: db_hgp_symfony
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hgp_symfony
      MYSQL_USER: user_hgp
      MYSQL_PASSWORD: hgp_36
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php_hgp_symfony
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/hgp_symfony
    depends_on:
      - database

  nginx:
    container_name: nginx_hgp_symfony
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/hgp_symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      PMA_HOST: database
    depends_on:
      - database