controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    defaults:
        _controller: 'App\Controller\HomeController::index'